name: Upload data

on:
  push:
  pull_request:

jobs:
  runscript:
    name: Validate Detekt and Storyguide.md file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if Rules are sync
        run:  bash .github/workflows/script/validate_detekt_scrip.sh
      - name: Check if Version is sync
        run:  bash .github/workflows/script/validate_detekt_version_scrip.sh
