name: Upload data

on:
  push:
  pull_request:

jobs:
  runscript:
    name: Validate Detekt and Storyguide.md file
    runs-on: ubuntu-latest
    steps:
      - name: Check if Rules are sync
        run:  sh config/script/./validate_detekt_scrip.sh
      - name: Check if Version is sync
        run:  sh config/script/./validate_detekt_version_scrip.sh
